// 此脚本及xiaoyu文件夹下所有脚本，由create_xiaoyu编写

#priority 1

import crafttweaker.item.IIngredient;

import mods.jei.JEI;

var JEIhide as IIngredient[] = [
    <aeadditions:terminal.universal.wireless>,
    <jaopca:avaritia_singularity.alumina>,
    <jaopca:avaritia_singularity.aluminium>,
    <jaopca:avaritia_singularity.beryllium>,
    <jaopca:avaritia_singularity.calcium>,
    <jaopca:avaritia_singularity.carbon>,
    <jaopca:avaritia_singularity.hydrogen>,
    <jaopca:avaritia_singularity.magnesia>,
    <jaopca:avaritia_singularity.magnesium>,
    <jaopca:avaritia_singularity.methane>,
    <jaopca:avaritia_singularity.nitrate>,
    <jaopca:avaritia_singularity.nitrogen>,
    <jaopca:avaritia_singularity.oxygen>,
    <jaopca:avaritia_singularity.phosphorus>,
    <jaopca:avaritia_singularity.potassium>,
    <jaopca:avaritia_singularity.quartz_black>,
    <jaopca:avaritia_singularity.silica>,
    <jaopca:avaritia_singularity.sulfur>,
    <jaopca:avaritia_singularity.zinc>,
    <jaopca:block.alumina>,
    <jaopca:block.aluminium>,
    <jaopca:block.beryllium>,
    <jaopca:block.calcium>,
    <jaopca:block.carbon>,
    <jaopca:block.hydrogen>,
    <jaopca:block.magnesia>,
    <jaopca:block.magnesium>,
    <jaopca:block.methane>,
    <jaopca:block.nitrate>,
    <jaopca:block.nitrogen>,
    <jaopca:block.oxygen>,
    <jaopca:block.phosphorus>,
    <jaopca:block.potassium>,
    <jaopca:block.silica>,
    <jaopca:block.sulfur>,
    <jaopca:block.zinc>,
    <jaopca:mysticalagriculture_crop.alumina>,
    <jaopca:mysticalagriculture_crop.beryllium>,
    <jaopca:mysticalagriculture_crop.calcium>,
    <jaopca:mysticalagriculture_crop.carbon>,
    <jaopca:mysticalagriculture_crop.hydrogen>,
    <jaopca:mysticalagriculture_crop.magnesia>,
    <jaopca:mysticalagriculture_crop.magnesium>,
    <jaopca:mysticalagriculture_crop.methane>,
    <jaopca:mysticalagriculture_crop.nitrate>,
    <jaopca:mysticalagriculture_crop.nitrogen>,
    <jaopca:mysticalagriculture_crop.oxygen>,
    <jaopca:mysticalagriculture_crop.phosphorus>,
    <jaopca:mysticalagriculture_crop.potassium>,
    <jaopca:mysticalagriculture_crop.silica>,
    <jaopca:dust.alumina>,
    <jaopca:dust.aluminium>,
    <jaopca:dust.beryllium>,
    <jaopca:dust.calcium>,
    <jaopca:dust.carbon>,
    <jaopca:dust.hydrogen>,
    <jaopca:dust.magnesia>,
    <jaopca:dust.magnesium>,
    <jaopca:dust.methane>,
    <jaopca:dust.nitrate>,
    <jaopca:dust.nitrogen>,
    <jaopca:dust.oxygen>,
    <jaopca:dust.phosphorus>,
    <jaopca:dust.potassium>,
    <jaopca:dust.silica>,
    <jaopca:dust.zinc>,
    <jaopca:mysticalagriculture_crux.alumina>,
    <jaopca:mysticalagriculture_crux.beryllium>,
    <jaopca:mysticalagriculture_crux.calcium>,
    <jaopca:mysticalagriculture_crux.carbon>,
    <jaopca:mysticalagriculture_crux.hydrogen>,
    <jaopca:mysticalagriculture_crux.magnesia>,
    <jaopca:mysticalagriculture_crux.magnesium>,
    <jaopca:mysticalagriculture_crux.methane>,
    <jaopca:mysticalagriculture_crux.nitrate>,
    <jaopca:mysticalagriculture_crux.nitrogen>,
    <jaopca:mysticalagriculture_crux.oxygen>,
    <jaopca:mysticalagriculture_crux.phosphorus>,
    <jaopca:mysticalagriculture_crux.potassium>,
    <jaopca:mysticalagriculture_crux.silica>,
    <jaopca:mysticalagriculture_seeds.alumina>,
    <jaopca:mysticalagriculture_seeds.beryllium>,
    <jaopca:mysticalagriculture_seeds.calcium>,
    <jaopca:mysticalagriculture_seeds.carbon>,
    <jaopca:mysticalagriculture_seeds.hydrogen>,
    <jaopca:mysticalagriculture_seeds.magnesia>,
    <jaopca:mysticalagriculture_seeds.magnesium>,
    <jaopca:mysticalagriculture_seeds.methane>,
    <jaopca:mysticalagriculture_seeds.nitrate>,
    <jaopca:mysticalagriculture_seeds.nitrogen>,
    <jaopca:mysticalagriculture_seeds.oxygen>,
    <jaopca:mysticalagriculture_seeds.phosphorus>,
    <jaopca:mysticalagriculture_seeds.potassium>,
    <jaopca:mysticalagriculture_seeds.silica>,
    <jaopca:mysticalagriculture_essence.alumina>,
    <jaopca:mysticalagriculture_essence.beryllium>,
    <jaopca:mysticalagriculture_essence.calcium>,
    <jaopca:mysticalagriculture_essence.carbon>,
    <jaopca:mysticalagriculture_essence.hydrogen>,
    <jaopca:mysticalagriculture_essence.magnesia>,
    <jaopca:mysticalagriculture_essence.magnesium>,
    <jaopca:mysticalagriculture_essence.methane>,
    <jaopca:mysticalagriculture_essence.nitrate>,
    <jaopca:mysticalagriculture_essence.nitrogen>,
    <jaopca:mysticalagriculture_essence.oxygen>,
    <jaopca:mysticalagriculture_essence.phosphorus>,
    <jaopca:mysticalagriculture_essence.potassium>,
    <jaopca:mysticalagriculture_essence.silica>,
    <plustic:plustic.molten_alumite>,
    <forestry:resources:1>,
    <mekanism:oreblock:1>,
    <forestry:resources:2>,
    <mekanism:oreblock:2>,
    <mekanism:oreblock:4>,
];

for hide in JEIhide {
    JEI.removeAndHide(hide, false);
}